// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlelnwgctxadufwncxez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZWxud2djdHhhZHVmd25jeGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODU2NTEsImV4cCI6MjA3Mzg2MTY1MX0.4i6snXcRa9CfHbHVEO6Qn_Qqmo770g001QyUdcJzN6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});